overwrite: true
schema: "graphql/schema.graphql"
documents: ["graphql/**/*.graphql", "src/**/*.ts"]

generates:
  src/graphql.generated.ts:
    plugins:
      - "typescript"
      - "typescript-document-nodes"
      - "typescript-operations"
