name: Generate

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate
        run: bun run start
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update generated images"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
